spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lovekeeper
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 ?? ?? (????)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA ?? (??????? ??? ? ??)
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, validate, update ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true